# Generated by Django 4.1.6 on 2023-02-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateField(null=True)),
                ("date_updated", models.DateField(null=True)),
                ("commitments", models.CharField(max_length=1024)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_due", models.DateField(null=True)),
                (
                    "contract_status",
                    models.CharField(
                        choices=[("open", "OPEN"), ("signed", "SIGNED")], max_length=64
                    ),
                ),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_company_name",
                        to="customers.customer",
                    ),
                ),
                (
                    "sales_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
