# Generated by Django 4.1.6 on 2023-02-06 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=1024)),
                (
                    "event_status",
                    models.CharField(
                        choices=[("open", "OPEN"), ("close", "CLOSED")], max_length=64
                    ),
                ),
                ("event_date", models.DateField(null=True)),
                ("created_date", models.DateField(null=True)),
                ("updated_date", models.DateField(null=True)),
                ("attendees", models.PositiveSmallIntegerField(null=True)),
                ("note", models.TextField()),
                (
                    "company_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_company_name",
                        to="customers.customer",
                    ),
                ),
                (
                    "sales_contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_sales_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "support_contact",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_contact_support",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
